// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://opkoescrnnepcxlsiuny.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im9wa29lc2Nybm5lcGN4bHNpdW55Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3Nzk5MDc0MzMsImV4cCI6MjA5NTQ4MzQzM30.PVlzTinrnyUQI8AEiF5ZNtuDG1WHcmHdEo4eNsSfdxE";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});